- hosts: WS2012
  gather_facts: no
  tasks:
  - win_shell: Set-DnsClientServerAddress -InterfaceIndex 12 -ServerAddresses ("10.104.2.70","10.211.101.20")
  - win_domain_membership:
      dns_domain_name: ansible.asir
      hostname: "{{ inventory_hostname }}"
      domain_admin_user: administrador@ansible.asir
      domain_admin_password: server.2018ws
      domain_ou_path: "OU=Windows,OU=Servidores,DC=ansible,DC=asir"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required
